### ISSUE TITLE
it dont work

### ISSUE THREAD

**Issue by averwhy** [pahaze/AudacityRichPresence#1]
im running it on windows 10. does it require anything? its just stuck on black command prompt screen

**Comment by pahaze** [comment]
Oh, sorry about the long wait for a response. I forgot to fix the token. I'll fix it 👍

**Comment by pahaze** [comment]
> im running it on windows 10. does it require anything? its just stuck on black command prompt screen

Also, it's supposed to be blank. I'm working on a version that sits in the taskbar as a icon instead of a blank CMD window 😄

**Comment by pahaze** [comment]
Once again, sorry for the long wait. Try the new release, if something is wrong please don't hesitate to reopen the issue!

**Comment by averwhy** [comment]
Oh, no worries for the wait. I'll check out the new release
